ls:
  .dir: kebab-case
  .*: kebab-case

ignore:
  - .git
  - .husky
  - .turbo
  - .vscode
  - dist
  - node_modules
  - README.md
  - "packages/*/.turbo"
  - "packages/*/dist"
  - "packages/*/node_modules"
  - "packages/*/README.md"
