import fs from "node:fs";
import path from "node:path";

import chalk from "chalk";
import { kebabCase } from "lodash-es";
import openapiTS from "openapi-typescript";

interface ApiConfig {
  name: string;
  url: string;
  description: string;
}

const ROOT = path.resolve(import.meta.dirname, "..");
const SCRIPT_FILENAME = path.relative(ROOT, import.meta.filename);
const INPUTS: Array<ApiConfig> = [
  {
    name: "petStore",
    url: "https://petstore.swagger.io/v2/swagger.json",
    description: "https://petstore.swagger.io/",
  },
];

main();

async function main() {
  for (const apiConfig of INPUTS) {
    await genApiDefines(apiConfig);
  }
}

async function genApiDefines(apiConfig: ApiConfig) {
  const startTime = performance.now();
  const ast = await openapiTS(apiConfig.url);
  const outputFile = path.resolve(ROOT, `./src/generated/apis/api-${kebabCase(apiConfig.name)}.ts`);
  const outputFileName = path.relative(ROOT, outputFile);
  fs.writeFileSync(
    outputFile,
    [`// This file was auto generated by ${SCRIPT_FILENAME}`, "// @ts-nocheck", ast].join("\n"),
  );
  console.log(chalk.green(`Gen ${outputFileName} success! ${(performance.now() - startTime).toFixed(1)}ms`));
}
